-- ============================================================
--   Table : DerivativeExecution
-- ============================================================
create table DerivativeExecution
(
    tradeId                        VARCHAR2(128)          not null,
    portfolioId                    VARCHAR2(64)           not null,
    brokerExchangeId               VARCHAR2(64)           null    ,
    mic                            VARCHAR2(32)           null    ,
    userId                         VARCHAR2(64)           not null,
    imsId                          VARCHAR2(32)           not null,
    orderId                        VARCHAR2(128)          null    ,
    way                            VARCHAR2(1)            null
        constraint CKC_WAY_DERIVATI check (
            way is null or (way in ('2','B','S'))),
    quantity                       INTEGER                null    ,
    price                          FLOAT                  null    ,
    timestamp                      TIMESTAMP(3)           null    ,
    imsUserId                      VARCHAR2(32)           null    ,
    userData                       VARCHAR2(256)          null    ,
    marketData                     CLOB                   null    ,
    executionState                 VARCHAR2(1)            not null
        constraint CKC_EXECUTIONSTATE_DERIVATI check (
            executionState in ('n','c','u')),
    productId                      VARCHAR2(128)          null    ,
    context                        VARCHAR2(32)           default 'DEFAULT' null    ,
    toHedge                        NUMBER(1)              default 0 null    ,
    sessionId                      VARCHAR2(64)           null    ,
    hedgeUlId                      VARCHAR2(128)          null    ,
    hedgeRatio                     FLOAT                  default 1 null    ,
    hedgeUlSpot                    FLOAT                  null    ,
    hedgeProxyUlSpot               FLOAT                  null    ,
    exchangeFees                   FLOAT                  null    ,
    clearingFees                   FLOAT                  null    ,
    brokerageFees                  FLOAT                  null    ,
    crossTradeId                   VARCHAR2(128)          null    ,
    feesData                       VARCHAR2(128)          null    ,
    isComplete                     NUMBER(1)              null    ,
    ignoreInPosition               NUMBER(1)              null    ,
    marketTradeId                  VARCHAR2(128)          null    ,
    productToHedgeForex            FLOAT                  null    ,
    shortSellType                  VARCHAR2(32)           null    ,
    tradeType                      VARCHAR2(64)           null    ,
    currencyId                     VARCHAR2(3)            null    ,
    eventTimestamp                 TIMESTAMP(3)           null    ,
    version                        INTEGER                null    ,
    brokerName                     VARCHAR2(256)          null    ,
    immediateHedgePercent          FLOAT                  null    ,
    immediateHedgeStrategy         VARCHAR2(16)           null    ,
    originalOrderPrice             FLOAT                  null    ,
    originalOrderQuantity          INTEGER                null    ,
    orderTimestamp                 TIMESTAMP(3)           null    ,
    execMarketData                 CLOB                   null    ,
    settlementDate                 TIMESTAMP(3)           null    ,
    settlementFees                 FLOAT                  null    ,
    comments                       VARCHAR2(256)          null    ,
    imsChannelType                 INTEGER                default 100 null    ,
    ulId                           VARCHAR2(128)          null    ,
    productToUlForex               FLOAT                  null    ,
    spot                           FLOAT                  null    ,
    theoriticalPrice               FLOAT                  null    ,
    delta                          FLOAT                  null    ,
    gamma                          FLOAT                  null    ,
    volatility                     FLOAT                  null    ,
    vega                           FLOAT                  null    ,
    theta                          FLOAT                  null    ,
    rho                            FLOAT                  null    ,
    mu                             FLOAT                  null    ,
    deltaUnderlying                FLOAT                  null    ,
    gammaUnderlying                FLOAT                  null    ,
    vegaUnderlying                 FLOAT                  null    ,
    thetaUnderlying                FLOAT                  null    ,
    rhoUnderlying                  FLOAT                  null    ,
    muUnderlying                   FLOAT                  null    ,
    spreadAmount                   FLOAT                  null    ,
    spreadDistribution             FLOAT                  null    ,
    askShiftUnit                   VARCHAR2(16)           null    ,
    askShiftValue                  FLOAT                  null    ,
    bidShiftUnit                   VARCHAR2(16)           null    ,
    bidShiftValue                  FLOAT                  null    ,
    priceShiftUnit                 VARCHAR2(16)           null    ,
    priceShiftValue                FLOAT                  null    ,
    askTickShift                   INTEGER                null    ,
    bidTickShift                   INTEGER                null    ,
    rawPrice                       FLOAT                  null    ,
    marketToPricingForex           FLOAT                  null    ,
    biases                         CLOB                   null    ,
    constraint PK_DERIVATIVEEXEC primary key (tradeId)
)
/
